import LegalLayout from './LegalLayout';

export default function Disclaimer() {
  return (
    <LegalLayout title="Disclaimer" subtitle="Important limitations and disclaimers for using Sahu Sphere." updated="January 1, 2026">
      <div className="legal-content">
        <h2>1. General Disclaimer</h2>
        <p>
          The information and tools provided on Sahu Sphere (sahusphere.com) are offered "as is" without any representations or warranties, express or implied. By using our website and services, you accept these disclaimers in full.
        </p>

        <h2>2. No Professional Advice</h2>
        <p>
          The content on Sahu Sphere is provided for general informational and productivity purposes only. Nothing on this website constitutes legal, financial, medical, professional, or any other type of advice. You should always seek professional guidance for matters requiring expert knowledge.
        </p>

        <h2>3. Accuracy of Information</h2>
        <p>While we strive to keep the information on Sahu Sphere accurate and up-to-date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on our website.</p>

        <h2>4. Tool Output Disclaimer</h2>
        <p>
          Sahu Sphere provides tools such as the Image to PDF Converter. The output generated by these tools depends entirely on the input provided by the user. We disclaim all liability for:
        </p>
        <ul>
          <li>The quality of PDF output (which depends on input image quality)</li>
          <li>Loss of data during conversion</li>
          <li>Incompatibility with specific PDF readers or systems</li>
          <li>Any errors introduced during the conversion process</li>
          <li>File corruption or data loss</li>
        </ul>
        <p>We strongly recommend keeping original copies of all files before conversion.</p>

        <h2>5. Browser Compatibility</h2>
        <p>
          Our tools rely on modern web browser capabilities. While we test our tools across major browsers, we cannot guarantee perfect functionality across all browser versions, operating systems, or device configurations. Older browsers may not support all features.
        </p>

        <h2>6. No Warranty of Availability</h2>
        <p>
          We do not guarantee that our website or tools will be available at all times. We reserve the right to modify, suspend, or discontinue the service at any time without notice. We are not responsible for any inconvenience or loss caused by service unavailability.
        </p>

        <h2>7. Internet and Device Risks</h2>
        <p>
          The transmission of information via the internet is not completely secure. Although we do not transmit your files (processing is done client-side), we cannot guarantee the security of data transmitted to our website through contact forms or other means.
        </p>

        <h2>8. Third-Party Websites</h2>
        <p>
          Our website may contain links to third-party websites for your convenience and information. These links do not signify our endorsement of the third-party websites. We have no control over the content or nature of these sites and take no responsibility for the content, privacy policies, or practices of any third-party websites.
        </p>

        <h2>9. Copyright and Intellectual Property</h2>
        <p>
          Users are solely responsible for ensuring that the images and files they process with our tools do not infringe on any third-party copyrights, trademarks, or other intellectual property rights. Sahu Sphere is not responsible for any copyright infringement committed by users.
        </p>

        <h2>10. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by applicable law, Sahu Sphere and its operators will not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of our services, including but not limited to loss of data, loss of revenue, or loss of business opportunities.
        </p>

        <h2>11. User Responsibility</h2>
        <p>Users are solely responsible for:</p>
        <ul>
          <li>The legality of the content they process using our tools</li>
          <li>Maintaining backups of their original files</li>
          <li>Verifying the accuracy and quality of converted files</li>
          <li>Compliance with applicable laws in their jurisdiction</li>
          <li>Any consequences arising from the use of converted files</li>
        </ul>

        <h2>12. Changes to This Disclaimer</h2>
        <p>We reserve the right to modify this disclaimer at any time. Changes will be effective immediately upon posting. Continued use of our website constitutes acceptance of the updated disclaimer.</p>

        <h2>13. Governing Law</h2>
        <p>This disclaimer is governed by and construed in accordance with the laws of India. Any disputes arising from this disclaimer shall be subject to the jurisdiction of Indian courts.</p>

        <h2>14. Contact Us</h2>
        <p>For questions about this disclaimer, contact us:</p>
        <ul>
          <li><strong>Email:</strong> info@sahusphere.com</li>
          <li><strong>Website:</strong> sahusphere.com</li>
        </ul>
      </div>
    </LegalLayout>
  );
}
